version: '3.4'

networks:
  docker-api:
    driver: bridge

services:
  chat.webapi:
    image: ${DOCKER_REGISTRY-}chatwebapi
    container_name: chat-web-api
    build:
      context: .
      dockerfile: Chat.WebApi/Dockerfile
    ports:
      - "5000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_db;port=5432;database=chatDb;username=admin;password=password"
    networks:
      - docker-api

  postgres_db:
    image: postgres:13
    container_name: postgres-db
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "chatDb"
    networks:
      - docker-api

  frontend:
    image: chat-view
    container_name: chat-view
    build:
      context: ../client/chat-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
      - chat.webapi

